CREATE DATABASE tower_defense;
USE tower_defense;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100),
  email VARCHAR(100) UNIQUE,
  password VARCHAR(255)
);

CREATE TABLE scores (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100),
  score INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);